// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCUqkS9te1fgwftv71lGtGYjUX734WkLY',
    appId: '1:384845137165:web:fab6e6c9fb6f364e699c44',
    messagingSenderId: '384845137165',
    projectId: 'campushub-dbb9d',
    authDomain: 'campushub-dbb9d.firebaseapp.com',
    storageBucket: 'campushub-dbb9d.firebasestorage.app',
    measurementId: 'G-NJCQZ85WCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD248CaQNdKeOQHxO9SrCxPY9KUkiXw1Iw',
    appId: '1:384845137165:android:3e615ad76ea37688699c44',
    messagingSenderId: '384845137165',
    projectId: 'campushub-dbb9d',
    storageBucket: 'campushub-dbb9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARoAhDtEesuax-D7xwZR_dKeNNodVA68I',
    appId: '1:384845137165:ios:d6d1bc4a1d70074c699c44',
    messagingSenderId: '384845137165',
    projectId: 'campushub-dbb9d',
    storageBucket: 'campushub-dbb9d.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARoAhDtEesuax-D7xwZR_dKeNNodVA68I',
    appId: '1:384845137165:ios:d6d1bc4a1d70074c699c44',
    messagingSenderId: '384845137165',
    projectId: 'campushub-dbb9d',
    storageBucket: 'campushub-dbb9d.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCUqkS9te1fgwftv71lGtGYjUX734WkLY',
    appId: '1:384845137165:web:be76e079187f1b6b699c44',
    messagingSenderId: '384845137165',
    projectId: 'campushub-dbb9d',
    authDomain: 'campushub-dbb9d.firebaseapp.com',
    storageBucket: 'campushub-dbb9d.firebasestorage.app',
    measurementId: 'G-YDSRX41N6X',
  );
}
